/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.doxa.jinputmining.vista;

import com.doxa.jinputmining.controller.GenerarRotacion;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author BlackSpider
 */
public class CalcularIr extends javax.swing.JPanel {

    /**
     * Creates new form CalcularIr
     */
    
    private String ruta;
    
    
    public CalcularIr(String ruta) {
        initComponents();
        
        this.ruta = ruta;
        this.jdc_FechaIni.setDateFormatString("dd/MM/yyyy");
        this.jdc_FechaFin.setDateFormatString("dd/MM/yyyy");
    }

    public String getRuta() {
        return ruta;
    }

    public void setRuta(String ruta) {
        this.ruta = ruta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdc_FechaFin = new com.toedter.calendar.JDateChooser();
        btn_GenerarIR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jdc_FechaIni = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        tfFamIni = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfFamFin = new javax.swing.JTextField();

        btn_GenerarIR.setText("Generar");
        btn_GenerarIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GenerarIRActionPerformed(evt);
            }
        });

        jLabel2.setText("Fecha inicio:");

        jLabel8.setText("Fecha Fin:");

        jLabel9.setText("Familia ID inicio:");

        tfFamIni.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel10.setText("Familia ID Fin:");

        tfFamFin.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_GenerarIR)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(27, 27, 27)
                                        .addComponent(tfFamFin, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfFamIni, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(70, 70, 70))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jdc_FechaIni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jdc_FechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(191, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jdc_FechaIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jdc_FechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(tfFamIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfFamFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(btn_GenerarIR)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_GenerarIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GenerarIRActionPerformed
        // TODO add your handling code here:
        
        if (ruta.length() <= 0){

           JOptionPane.showMessageDialog(this,"Selecciona un destino para la salida del archivo" ,"Error",JOptionPane.ERROR_MESSAGE);

            return;

        }

        if (!checkCamposRI()){

            JOptionPane.showMessageDialog(this,"Verificacion de Campos" ,"Rellene todos los campos",JOptionPane.INFORMATION_MESSAGE);

            return;

        }

        String fechaInicio = new SimpleDateFormat("yyyy-MM-dd").format(this.jdc_FechaIni.getDate());
        String fechaFin = new SimpleDateFormat("yyyy-MM-dd").format(this.jdc_FechaFin.getDate());

        int famIni = Integer.parseInt(this.tfFamIni.getText());
        int famFin = Integer.parseInt(this.tfFamFin.getText());

        GenerarRotacion gr = new GenerarRotacion(famIni, famFin, fechaInicio, fechaFin, ruta);

        gr.generarRI();
    }//GEN-LAST:event_btn_GenerarIRActionPerformed

    
     private boolean checkCamposRI(){
        
      if (this.jdc_FechaIni.getDate() == null){
      
          return false;

      }
      
      if (this.jdc_FechaFin.getDate() == null){
      
          return false;

      }
      
      if (this.tfFamIni.getText().length()<=0){
      
          return false;

      }
      
      if (this.tfFamFin.getText().length()<=0){
      
          return false;

      }
      
              
        return true;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_GenerarIR;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JDateChooser jdc_FechaFin;
    private com.toedter.calendar.JDateChooser jdc_FechaIni;
    private javax.swing.JTextField tfFamFin;
    private javax.swing.JTextField tfFamIni;
    // End of variables declaration//GEN-END:variables
}
