/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.doxa.jinputmining.vista;

import com.doxa.jinputmining.controller.GenerarDataSetMinaje;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author BlackSpider
 */
public class DataSetFpGrwth extends javax.swing.JPanel {

    /**
     * Creates new form DataSetFpGrwth
     */
    private String ruta;

    public String getRuta() {
        return ruta;
    }

    public void setRuta(String ruta) {
        this.ruta = ruta;
    }

    public DataSetFpGrwth(String ruta) {
        initComponents();
        this.ruta = ruta;
        this.jdc_FechaIni.setDateFormatString("dd/MM/yyyy");
        this.jdc_FechaFin.setDateFormatString("dd/MM/yyyy");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_generar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tfFam = new javax.swing.JTextField();
        jdc_FechaIni = new com.toedter.calendar.JDateChooser();
        jdc_FechaFin = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_Momento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        chb_onlyFam = new javax.swing.JCheckBox();

        btn_generar.setText("Generar");
        btn_generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarActionPerformed(evt);
            }
        });

        jLabel9.setText("Familia ID:");

        tfFam.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel2.setText("Fecha inicio:");

        jLabel8.setText("Fecha Fin:");

        jLabel1.setText("Momento:");

        chb_onlyFam.setText("Solo transacciones con Familia ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_generar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jdc_FechaIni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jdc_FechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfFam, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chb_onlyFam))
                    .addComponent(tf_Momento))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jdc_FechaIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jdc_FechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Momento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfFam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chb_onlyFam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(btn_generar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarActionPerformed
        // TODO add your handling code here:

        if (ruta.length() <= 0) {

            JOptionPane.showMessageDialog(this, "Selecciona un destino para la salida del archivo", "Error", JOptionPane.ERROR_MESSAGE);

            return;

        }

        if (!checkCamposRI()) {

            JOptionPane.showMessageDialog(this, "Verificacion de Campos", "Rellene todos los campos", JOptionPane.INFORMATION_MESSAGE);

            return;

        }

        String fechaInicio = new SimpleDateFormat("yyyy-MM-dd").format(this.jdc_FechaIni.getDate());
        String fechaFin = new SimpleDateFormat("yyyy-MM-dd").format(this.jdc_FechaFin.getDate());

        int fam = Integer.parseInt(this.tfFam.getText());

        GenerarDataSetMinaje gdsm = new GenerarDataSetMinaje(fechaInicio, fechaFin, this.tf_Momento.getText(), this.ruta, fam ,this.chb_onlyFam.isSelected());
        gdsm.generarDataSet();

    }//GEN-LAST:event_btn_generarActionPerformed
    private boolean checkCamposRI() {

        if (this.jdc_FechaIni.getDate() == null) {

            return false;

        }

        if (this.jdc_FechaFin.getDate() == null) {

            return false;

        }

        if (this.tfFam.getText().length() <= 0) {

            return false;

        }

        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_generar;
    private javax.swing.JCheckBox chb_onlyFam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JDateChooser jdc_FechaFin;
    private com.toedter.calendar.JDateChooser jdc_FechaIni;
    private javax.swing.JTextField tfFam;
    private javax.swing.JTextField tf_Momento;
    // End of variables declaration//GEN-END:variables
}
